### ISSUE TITLE
Human joint points

### ISSUE THREAD

**Issue by jianlai123-123** [HowieMa/TransFusion-Pose#5]
Hello! I'd like to ask about the human joints. What are the names of 3: rank and 6: lank? I hope to get your reply. thank you! @HowieMa

**Comment by HowieMa** [comment]
It stands for "right ankle" and "left ankle". I directly adopt the code from [multiview-human-pose](https://github.com/microsoft/multiview-human-pose-estimation-pytorch/blob/60039980dbb4141b04f6ff5a98794a5a7bc1d78e/lib/dataset/multiview_h36m.py)

**Comment by jianlai123-123** [comment]
> It stands for "right ankle" and "left ankle". I directly adopt the code from [multiview-human-pose](https://github.com/microsoft/multiview-human-pose-estimation-pytorch/blob/60039980dbb4141b04f6ff5a98794a5a7bc1d78e/lib/dataset/multiview_h36m.py)

Thank you for your reply

**Comment by jianlai123-123** [comment]
Hello, I have another question about the key points. Many projects use 16 key points, and this article uses 20. I can't find this structure diagram, so I want to ask. In posture estimation, 10: upper neck and 13: top of head, which key point points to them respectively. 0: root points to 7: abdomen, 7: abdomen points to 8: chest, is that right? Looking forward to your reply, thank you! 
@HowieMa

**Comment by HowieMa** [comment]
Hi, thanks for asking. 

Firstly, different datasets have different keypoint definitions of the human joint. 
For example, the COCO dataset has 17 key points, as shown below: 
<img width="856" alt="image" src="https://user-images.githubusercontent.com/25797674/203210930-1b74161e-a965-4792-b971-90bda497fd27.png">.
You can also find some examples on their official [website](https://cocodataset.org/#keypoints-2020).  

For the MPII dataset, it has 16 key points, you can find the definition at [our code](https://github.com/HowieMa/TransFusion-Pose/blob/main/lib/dataset/mpii.py#L23). 
<img width="197" alt="image" src="https://user-images.githubusercontent.com/25797674/203211745-c66d7080-dce0-4bea-a52a-0c2bc2b9522b.png">

For the Human 3.6M, it has 17 key points, 
<img width="252" alt="image" src="https://user-images.githubusercontent.com/25797674/203212480-d007f0a4-124a-4531-95ac-a0abc982dcb4.png">

Thus, there is no "root" joint for COCO, but there is "root" joint in MPII and Human 3.6M. Usually, the root joint is around the belly or waist. 
Note that, all of these key points are defined by the dataset **officially**, rather than a special definition in our paper. 

Secondly, as said above, the 20 union key points are adapted from the multiview-human-pose. This is a **union** of keypoint graphs of both Human 3.6M and MPII, rather than a special type of graph. That's why there are both "neck" and "upper neck" in the 20-joint set. 

<img width="239" alt="image" src="https://user-images.githubusercontent.com/25797674/203213356-ccc511f2-4e3b-4974-8c51-ee2f6632c47d.png">

**Comment by jianlai123-123** [comment]
Thank you for your reply
