### ISSUE TITLE
what about multi-person? 

### ISSUE THREAD

**Issue by tianyu06030020** [HowieMa/TransFusion-Pose#9]
Hello, can it works well when multi-person in cross-view?

**Comment by HowieMa** [comment]
Thanks. It's a good question. In short, the answer is no. This network only focuses on single-person, similar to Epipolar Transformers.  
To make it work on multi-person, you have to modify the architecture since multi-person multi-view setting requires aligning different persons from different views.

**Comment by tianyu06030020** [comment]
thanks your nicely reply, i will try lately!
